@startuml Buy_an_offer 

actor User


User -> ServiceRequester: select offer
ServiceRequester -> BuyProcessor: select offer
BuyProcessor -> Service: deploy service
BuyProcessor --> ServiceRequester: service link
ServiceRequester --> User: service link
User -> Service: use service


@enduml