@startuml Execute_Request 

actor User


User -> ServiceRequester: select OTF provider
ServiceRequester -> OTFProvider: send request parameters
database RequestDatabse
OTFProvider -> RequestDatabse: create request
loop until no more questions
    OTFProvider -> ServiceRequester: interview question
    ServiceRequester -> User: interview question
    User --> ServiceRequester: interview answer
    ServiceRequester --> OTFProvider: interview question
    OTFProvider -> RequestDatabse: update request
end
OTFProvider -> ConfigurationProcess: spawn configuration process
ConfigurationProcess -> ConfigurationProcess: compute configuration
ConfigurationProcess -> BuyProcessor: save offer
database OfferDatabase
BuyProcessor -> OfferDatabase:  save offer


@enduml