apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
  - name: proseco-container
    imagePullPolicy: Always
    image: nexus.cs.upb.de/sfb901-testbed/proseco_container
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
    env:
    - name: EXECUTOR_ADDRESS_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: EXECUTOR_ADDRESS
      value: "$(EXECUTOR_ADDRESS_HOST):7000"
    ports:
    - name: executor-port
      containerPort: 7000
    volumeMounts:
    - name: docker 
      mountPath: /var/run/docker.sock
  volumes:
    - name: docker 
      hostPath:
        path: /var/run/docker.sock
        type: ""