kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: "executor-id"
  labels:
    name: "${EXECUTOR_ID}"
    run: "${EXECUTOR_ID}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "${EXECUTOR_ID}"
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
