package de.upb.crc901.otftestbed.commons.general;

public enum JobState {
  CREATED, PROSECO_NEEDS_MORE_INFOS, REQUEST_PROCESSOR_NEEDS_MORE_INFOS, READY_TO_CONFIGURE, CONFIGURING, WAITING_FOR_VERIFICATION, VERIFIED, ACCEPTED, DECLINED, INVALID, BUILDING, PUBLISHING, DONE
}
