### General
projectName: commons
# must end with / and may not start with /
projectPath: commons/

### Jenkinsfile
# set to true if this project should trigger other projects
# for this list, the user is asked whether or not they should be triggered
triggerOtherProjects: true
triggerList: [
            {project: "OTFTestbed_commons_commons_otf_provider"},
            {project: "OTFTestbed_commons_service_spec_uploader"},
            {project: "OTFTestbed_execution-gateway_kubernetes_executor_spawner"},
            {project: "OTFTestbed_local_client_user_creator"},
            {project: "OTFTestbed_local_client_service_requester_new"},
            {project: "OTFTestbed_market_provider_buy_processor"},
            {project: "OTFTestbed_market_provider_credential_issuer"},
            {project: "OTFTestbed_market_provider_otfp_registry_new"},
            {project: "OTFTestbed_market_provider_review_board"},
            #{project: "OTFTestbed_market_provider_reputation_system"}, #this project isnt part of jenkins atm
            {project: "OTFTestbed_market_provider_system_manager"},
            {project: "OTFTestbed_otf_provider_composition_analysis"},
            #{project: "OTFTestbed_otf_provider_otf_fuzzy_matcher"}, # triggered from OTFTestbed_commons_commons_otf_provider
            #{project: "OTFTestbed_otf_provider_otf_proseco_configurator"}, # triggered from OTFTestbed_commons_commons_otf_provider
            {project: "OTFTestbed_otf_provider_otfp_policy_provider"}
            #{project: "OTFTestbed_otf_provider_otfp_refactored_gatekeeper"} # triggered from OTFTestbed_commons_commons_otf_provider
            ]
# set to true if this proejct should trigger other projects
# user is *not* asked whether or not they should be build.
# build is triggered after the docker stage is done if no previous step failed
forceTriggerProjects: false
forceList: []
uploadDocker: false
uploadArtifacts: true
useSonarqube: true

### Jenkins project
branch: "*/develop"
# If any other folder then the projects folder should be included
# for more includes seperate with a space
includeRegions: 
# Same as include but nothing is excluded by default
excludeRegions: 
# Might be used if you need a different jenkinsfile for any reason (for example to test a specific branch without uploading)
jenkinsfileName: Jenkinsfile
# Token to trigger the build
token: iogsdlkmk

###DOCKER CONFIGURATION
springBoot: false
jetty: false

###SPRING BOOT CONFIGURATION (if used)
# the name of the service_specification used (i.e. your service_specification is named {specificationName}.yaml)
specificationName: example_service_specification
# currently not used, as our versioning is done by docker tags. However maybe relevant in the future
jarVersion: 0.1.0
baseGenerationPackage: de.upb.crc901.otftestbed.rep_jugde.generated.spring_server
baseImplementationPackage:  de.upb.crc901.otftestbed.rep_jugde.impl
#internal port (don't change this, if you don't know what you are doing)
port: 8080
#specifies whether a mongo connection should be established
mongoDependency: false
# mongo config stuff
mongoIP: 131.234.28.160
mongoPort: 27017
mongoDB: otf-provider-data
# only change this!
mongoCollection: service_specifications
