apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  namespace: otf-prov
type: Opaque
data:
  username:
    Z3JhZGxldXNlcgo=
  password:
    NWx2NUh4d3IqNjR2Cg==
  host:
    bmV4dXMuY3MudXBiLmRlL3NmYjkwMS10ZXN0YmVkLwo=
