apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: otf-prov
spec:
  restartPolicy: Never
  containers:
  - name: proseco-container
    imagePullPolicy: Always
    image: nexus.cs.upb.de/sfb901-testbed/proseco_container
    volumeMounts:
    - name: docker 
      mountPath: /var/run/docker.sock
    env:
    - name: REQUEST_UUID
      value: d2cb3fa7-6895-481b-a11d-9401c09bcd38
    - name: OTFP_UUID
      value: 103a151b-9be2-4b79-947d-f2cb4a81e220
    - name: REQUEST_DB_HOST
      value: REQUEST_DB_HOST_REF
    - name: REQUEST_DB_HOST_REF
      value: '131.234.28.160'
    - name: REQUEST_DB_PORT
      value: '27017'
    - name: REQUEST_DB_USER
      valueFrom:
        secretKeyRef:
          name: request-db-secret
          key: username
    - name: REQUEST_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: request-db-secret
          key: password
    - name: DOCKER_USER
      valueFrom:
        secretKeyRef:
          name: docker-secret
          key: username
    - name: DOCKER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: docker-secret
          key: password
    - name: DOCKER_HOST
      valueFrom:
        secretKeyRef:
          name: docker-secret
          key: host
  volumes:
    - name: docker 
      hostPath:
        path: /var/run/docker.sock
        type: ""