package de.upb.crc901.testbed.otfproviderregistry.gui;

/**
 * Events for the gui, s.t. the gui can be updated. SubjectEvents are generated by self-stabilization protocols in case the set of outgoing edges at
 * the node was modified.
 * 
 * @author Michael
 *
 */
public class SubjectEvent {

	private GUIEvent eventType;
	private Object[] data;

	public SubjectEvent(GUIEvent t, Object[] d) {
		this.eventType = t;
		this.data = d;
	}

	public GUIEvent getEventType() {
		return eventType;
	}

	public Object[] getData() {
		return data;
	}

	public String toString() {
		return "SubjectEvent[" + this.eventType.toString() + ", " + data.toString() + "]";
	}
	
}