version: '3'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    #command:  bash mkdir -p /etc/nginx/ssl/
    #command:  mkdir -p /var/www/public/
      
    ports: 
      - 443:443
    volumes:
      - /etc/ssl/private/your-nexus-url-goes-here.pem:/etc/nginx/ssl/your-nexus-url-goes-here.pem
      - /etc/ssl/private/your-nexus-url-goes-here.key:/etc/nginx/ssl/your-nexus-url-goes-here.key
      - /home/general/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/general/nginx/index.html:/var/www/public/index.html
